package flowexamples.e06

import flowexamples.e06.E06SoapFlow.echoNamespace
import org.intellij.lang.annotations.Language

@Suppress("JSUnresolvedVariable")
object E06ResponseTransformationScript {

    /*
        Converting the CapitalCityResponse to the SayHiResponse expected by the echo service exposed by our flow.

        Namespaces:
        - CountryInfoService: There is no namespace prefix defined for the response from the country info service.
                              In such cases prefixes are autogenerated: ns1, ns2 etc. Here we are therefore using
                              the generated "ns1_" prefix when referencing the CapitalCityResponse elements in the XML
                              compliant JSON format.
        - EchoService:        We are binding the echo namespace to the default namespace. We can therefore define
                              the SayHiResponse response elements without namespace prefix.
    */
    @Language("ES6")
    val capitalCityResponseToEchoResponseScript =
        """
        return (
          {
            _xmlns: {
              _default: '$echoNamespace'
            },
            
            SayHiResponse: {
              HiResponse: {
                _text: input.payload.ns1_CapitalCityResponse.ns1_CapitalCityResult._text
              }
            }
          }
        )
        """.trimIndent()
}