package flowexamples.e06

import flowexamples.e06.E06SoapFlows.countryInfoNamespace
import flowexamples.e06.E06SoapFlows.echoNamespace
import org.intellij.lang.annotations.Language

@Suppress("JSUnresolvedVariable")
object E06TransformationScripts {

    /*
        Converting the echo SayHi request to a request for the CapitalCity operation of the public CountryInfoService
        web service: http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?op=CapitalCity

        Namespaces:
        - EchoService:        In the soapApi.namespacePrefixMapping flow config we have defined the echo namespace as
                              the default. We can therefore access the SayHi request elements without namespace prefix.
        - CountryInfoService: We are binding the country info namespace to the "c" prefix, and are
                              therefore using the "c_" prefix to define the CapitalCity elements in the XML compliant
                              JSON format.
    */
    @Language("ES6")
    val echoRequestToCapitalCityRequestScript =
        """
        return (
          {
            _xmlns: {
              c: '$countryInfoNamespace'
            },
            
            c_CapitalCity: {
              c_sCountryISOCode: {
                _text: input.payload.SayHi.Hi._text
              }
            }
          }
        )
        """.trimIndent()

    /*
        Converting the CapitalCityResponse to the SayHiResponse expected by the echo service exposed by our flow.

        Namespaces:
        - CountryInfoService: There is no namespace prefix defined for the response from the country info service.
                              In such cases prefixes are autogenerated: ns1, ns2 etc. Here we are therefore using
                              the generated "ns1_" prefix when referencing the CapitalCityResponse elements in the XML
                              compliant JSON format.
        - EchoService:        We are binding the echo namespace to the default namespace. We can therefore define
                              the SayHiResponse response elements without namespace prefix.
    */
    @Language("ES6")
    val capitalCityResponseToEchoResponseScript =
        """
        return (
          {
            _xmlns: {
              _default: '$echoNamespace'
            },
            
            SayHiResponse: {
              HiResponse: {
                _text: input.payload.ns1_CapitalCityResponse.ns1_CapitalCityResult._text
              }
            }
          }
        )
        """.trimIndent()
}